### ISSUE TITLE
Stop generating useless ChatGPT responses to spam others' repos

### ISSUE THREAD

**Issue by USA-RedDragon** [swarna1101/VeChain-Thor#1]
Title. You're not helping, you're being a pest

Some examples of spammy low-effort responses:
https://github.com/svix/svix-webhooks/issues/726#issuecomment-1364961225
https://github.com/svix/svix-webhooks/issues/453
https://github.com/svix/svix-webhooks/issues/714
https://github.com/bisq-network/bisq/issues/6486#issuecomment-1365107242
https://github.com/rysk-finance/dynamic-hedging/issues/311
https://github.com/bisq-network/bisq/issues/6398#issuecomment-1365108378

**Comment by NicoJuicy** [comment]
Why was this closed without a comment? Will it stop?
